### ISSUE TITLE
Error "java.lang.Throwable: Error loading workflow runs" in 1.17.0

### ISSUE THREAD

**Issue by kriegaex** [cunla/ghactions-manager#117]
Lately, the plugin started throwing exceptions when opening some projects (possibly because they are not in Git repositories or otherwise connected to GitHub or GitHub Actions, I am not sure. I use plugin 1.17.0 in IDEA 2023.3.4 Ultimate.

```text
java.lang.Throwable: Error loading workflow runs
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader.doLoadMore(WorkflowRunListLoader.kt:200)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader.access$doLoadMore(WorkflowRunListLoader.kt:32)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader$requestLoadMore$4$1.invoke(WorkflowRunListLoader.kt:97)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader$requestLoadMore$4$1.invoke(WorkflowRunListLoader.kt:97)
	at com.intellij.collaboration.async.CompletableFutureUtil.submitIOTask$lambda$1$lambda$0(CompletableFutureUtil.kt:58)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.collaboration.async.CompletableFutureUtil.submitIOTask$lambda$1(CompletableFutureUtil.kt:58)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/ghactions-manager/issues/117">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/ghactions-manager/issues/117/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/ghactions-manager/issues/117/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Hi @kriegaex, when getting this error:

- Do you have a GitHub account configured? (or are you using token in the plugin settings?)
- What is the git repository associated with the account? You mentioned it is not GitHub, what is the URL structure? Can you review JetBrains logs for what url is the plugin trying to query? Here is how to view IDE logs: https://plugins.jetbrains.com/docs/intellij/ide-infrastructure.html#error-reporting

**Comment by kriegaex** [comment]
> Do you have a GitHub account configured? (or are you using token in the plugin settings?)

GH account is configured in IDEA.

![image](https://github.com/cunla/ghactions-manager/assets/1537384/ac355528-bb35-47fd-bbe2-94e231519031)

> What is the git repository associated with the account? You mentioned it is not GitHub, what is the URL structure?

You misunderstood what I wrote. I said that the project I was opening was not associated with any Git repository at all, no local or remote one. I was simply a local Maven project. The one that was already open when opening that second one does have a GitHub connection, but it works fine.

> Can you review JetBrains logs for what url is the plugin trying to query?

I checked the logs, and the error occurred twice in the last few days:

```text
2024-03-07 13:27:46,081 [  17321]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/pzygielo/aspectj-maven-plugin/branches?page=1&per_page=100
2024-03-07 13:27:46,081 [  17321]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/pzygielo/aspectj-maven-plugin/actions/workflows?page=1&per_page=100
2024-03-07 13:27:46,083 [  17323]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/pzygielo/aspectj-maven-plugin/collaborators?page=1&per_page=100
2024-03-07 13:27:46,084 [  17324]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/pzygielo/aspectj-maven-plugin/actions/runs?page=1&per_page=30
2024-03-07 13:27:46,093 [  17333]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/mojohaus/aspectj-maven-plugin/collaborators?page=1&per_page=100
2024-03-07 13:27:46,094 [  17334]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/mojohaus/aspectj-maven-plugin/branches?page=1&per_page=100
2024-03-07 13:27:46,094 [  17334]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/mojohaus/aspectj-maven-plugin/actions/workflows?page=1&per_page=100
2024-03-07 13:27:46,117 [  17357]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/dev-aspectj/aspectj-maven-plugin/collaborators?page=1&per_page=100
2024-03-07 13:27:46,118 [  17358]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/dev-aspectj/aspectj-maven-plugin/branches?page=1&per_page=100
2024-03-07 13:27:46,118 [  17358]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/dev-aspectj/aspectj-maven-plugin/actions/workflows?page=1&per_page=100
2024-03-07 13:27:46,129 [  17369]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/kriegaex/aspectj-maven-plugin/collaborators?page=1&per_page=100
2024-03-07 13:27:46,157 [  17397]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/dev-aspectj/aspectj-maven-plugin/actions/runs?page=1&per_page=30
2024-03-07 13:27:46,160 [  17400]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/kriegaex/aspectj-maven-plugin/actions/runs?page=1&per_page=30
2024-03-07 13:27:46,168 [  17408]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/kriegaex/aspectj-maven-plugin/branches?page=1&per_page=100
2024-03-07 13:27:46,172 [  17412]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/kriegaex/aspectj-maven-plugin/actions/workflows?page=1&per_page=100
2024-03-07 13:27:46,421 [  17661]   INFO - #c.i.w.i.i.EntitiesOrphanageImpl - Update orphanage. 0 modules added
2024-03-07 13:27:46,424 [  17664]   INFO - #c.i.w.i.i.WorkspaceModelImpl - Project model updated to version 5 in 90 ms: Apply JPS storage (iml files)
2024-03-07 13:27:46,424 [  17664]   INFO - #c.i.w.i.i.EntitiesOrphanageImpl - Update orphanage. 0 modules added
2024-03-07 13:27:46,450 [  17690]   INFO - #c.i.w.i.i.j.s.DelayedProjectSynchronizer$Companion - Workspace model loaded from cache. Syncing real project state into workspace model in 727 ms. Thread[DefaultDispatcher-worker-30,5,main]
2024-03-07 13:27:46,615 [  17855]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [AspectJ]
2024-03-07 13:27:47,064 [  18304]   INFO - #c.i.d.WindowsDefenderCheckerActivity - status check is disabled
2024-03-07 13:27:47,313 [  18553] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Error loading workflow runs
java.lang.Throwable: Error loading workflow runs
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader.doLoadMore(WorkflowRunListLoader.kt:200)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader.access$doLoadMore(WorkflowRunListLoader.kt:32)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader$requestLoadMore$4$1.invoke(WorkflowRunListLoader.kt:97)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader$requestLoadMore$4$1.invoke(WorkflowRunListLoader.kt:97)
	at com.intellij.collaboration.async.CompletableFutureUtil.submitIOTask$lambda$1$lambda$0(CompletableFutureUtil.kt:58)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.collaboration.async.CompletableFutureUtil.submitIOTask$lambda$1(CompletableFutureUtil.kt:58)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-03-07 13:27:47,316 [  18556]   INFO - #o.j.j.b.i.CompilerReferenceIndex - backward reference index version doesn't exist
2024-03-07 13:27:47,317 [  18557]   INFO - #c.i.c.b.IsUpToDateCheckStartupActivity - suitable consumer is not found
2024-03-07 13:27:47,317 [  18557] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - IntelliJ IDEA 2023.3.4  Build #IU-233.14475.28
2024-03-07 13:27:47,318 [  18558] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-03-07 13:27:47,318 [  18558] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - OS: Windows 10
2024-03-07 13:27:47,318 [  18558] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Plugin to blame: GitHub Actions Manager version: 1.17.0
2024-03-07 13:27:47,319 [  18559] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Last Action: 
2024-03-07 13:27:47,321 [  18561]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/mojohaus/aspectj-maven-plugin/actions/runs?page=1&per_page=30
```

```text
2024-03-09 07:03:58,911 [149790151]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:04:28,911 [149820151]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:04:58,912 [149850152]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:05:28,912 [149880152]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:05:58,912 [149910152]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:06:28,913 [149940153]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:06:58,913 [149970153]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:07:28,914 [150000154]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:07:58,915 [150030155]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:08:28,917 [150060157]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:08:58,918 [150090158]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:09:28,918 [150120158]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/eclipse/org.aspectj/actions/runs?page=1&per_page=30
2024-03-09 07:09:33,923 [150125163] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Error loading workflow runs
java.lang.Throwable: Error loading workflow runs
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader.doLoadMore(WorkflowRunListLoader.kt:200)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader.access$doLoadMore(WorkflowRunListLoader.kt:32)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader$requestLoadMore$4$1.invoke(WorkflowRunListLoader.kt:97)
	at com.dsoftware.ghmanager.data.WorkflowRunListLoader$requestLoadMore$4$1.invoke(WorkflowRunListLoader.kt:97)
	at com.intellij.collaboration.async.CompletableFutureUtil.submitIOTask$lambda$1$lambda$0(CompletableFutureUtil.kt:58)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.collaboration.async.CompletableFutureUtil.submitIOTask$lambda$1(CompletableFutureUtil.kt:58)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-03-09 07:09:33,928 [150125168] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - IntelliJ IDEA 2023.3.4  Build #IU-233.14475.28
2024-03-09 07:09:33,928 [150125168] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-03-09 07:09:33,929 [150125169] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - OS: Windows 10
2024-03-09 07:09:33,929 [150125169] SEVERE - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Plugin to blame: GitHub Actions Manager version: 1.17.0
```

The second case was what I described above. The AspectJ project was open already, and the error occurred just when opening the second project, which has no Git repository.

**Comment by cunla** [comment]
I suspect the issue is the association of a GitHub account with a GitHub repository.

- What is the configured GitHub account name? is it `kriegaex`?
- Is there maybe more than one github account configured? if so, what are they?
- Does the configured github account(s) have access to `https://api.github.com/repos/kriegaex/aspectj-maven-plugin/actions/runs`? to `https://api.github.com/repos/dev-aspectj/aspectj-maven-plugin/actions/runs`? to `https://api.github.com/repos/eclipse/org.aspectj/actions/runs`?

**Comment by kriegaex** [comment]
* Yes, `kriegaex`.
* Only one account.
* Yes, the account has access to all those URLs. The plugin also works for the project in question. So, I do not know why it throws exceptions sometimes.

**Comment by cunla** [comment]
Does it still happen on 1.18?

**Comment by kriegaex** [comment]
As the error was intermittent, maybe ask me again in a week or so. So far, no, but I am unsure how long ago the plugin was updated here locally.
