### ISSUE TITLE
com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key ./.github/workflows/build-and-run-test.yml.

### ISSUE THREAD

**Issue by eonwabudo** [cunla/ghactions-manager#129]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

#### Stack trace

com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key ./.github/workflows/build-and-run-test.yml.
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2363)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2329)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2187)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4036)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4950)
	at com.dsoftware.ghmanager.psi.GitHubActionCache.resolveGithubAction(GitHubActionCache.kt:102)
	at com.dsoftware.ghmanager.psi.GitHubActionCache._init_$lambda$2(GitHubActionCache.kt:65)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

### Additional context

Plugin version: 1.21.1
IDE: IntelliJ IDEA 2024.1 (IU-241.14494.240)
OS: macOS 14.4.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/ghactions-manager/issues/129">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/ghactions-manager/issues/129/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/ghactions-manager/issues/129/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Thanks for reporting this. This is fixed in 1.21.3
